<?php

namespace Database\Factories\Resource;

use Illuminate\Database\Eloquent\Factories\Factory;

class UjianFactory extends Factory
{
    public function definition(): array
    {
        return [
            'id_paket_ujian' => PaketUjianFactory::new(),
            'id_paket_soal'  => PaketSoalFactory::new(),
            'nama' => $this->faker->randomElement([
                'SAS',
                'STS',
                'PAS',
                'PTS',
                'UTS',
                'UAS',
                'PAT',
                'UKK',
                'US',
                'USBK',
                'USBN',
                'UTBK',
                'PM',
                'PTM',
                'PAM',
                'PKK',
                'PKM',
                'SKK',
                'SKM',
                'MID',
                'RAP',
            ]) . " " . $this->faker->randomElement([
                'Matematika',
                'IPA',
                'IPS',
                'Bahasa Indonesia',
                'Bahasa Inggris',
                'Sejarah',
                'Geografi',
                'Ekonomi',
                'Sosiologi',
                'Fisika',
                'Kimia',
                'Biologi',
                'Seni Budaya',
                'PJOK',
                'PPKN',
                'TIK',
                'Informatika',
                'Prakarya',
                'Kewirausahaan',
                'Bimbingan Konseling',

                'Agama Islam',
                'Agama Kristen',
                'Agama Katolik',
                'Agama Hindu',
                'Agama Buddha',
                'Agama Konghucu',

                'Bahasa Arab',
                'Bahasa Mandarin',
                'Bahasa Jepang',
                'Bahasa Korea',
                'Bahasa Jerman',
                'Bahasa Prancis',
                'Bahasa Spanyol',
                'Bahasa Daerah',

                'Pemrograman Dasar',
                'Pemrograman Web',
                'Pemrograman Mobile',
                'Basis Data',
                'Jaringan Komputer',
                'Sistem Operasi',
                'Desain UI/UX',
                'Desain Grafis',
                'Multimedia',
                'Teknik Animasi',
                'Sistem Informasi',
                'Keamanan Siber',
                'Internet of Things (IoT)',
                'Kecerdasan Buatan (AI)',

                'Administrasi Perkantoran',
                'Akuntansi',
                'Bisnis Daring dan Pemasaran',
                'Manajemen Perkantoran',
                'Perpajakan',
                'Ekonomi Bisnis',
                'Manajemen Logistik',
                'Pariwisata',

                'Produktif RPL',
                'Produktif TKJ',
                'Produktif DKV',
                'Produktif OTKP',
                'Produktif BDP',
                'Produktif MM',
                'Teknik Mesin',
                'Teknik Otomotif',
                'Teknik Listrik',
                'Teknik Elektronika',
                'Teknik Pengelasan',
                'Teknik Audio Video',
                'Akomodasi Perhotelan',
                'Tata Boga',
                'Tata Busana',
                'Keperawatan',
                'Farmasi',
                'Agribisnis',
                'Perikanan',
                'Kelautan',

                'Pramuka',
                'PMR',
                'UKS',
                'KIR',
                'Musik',
                'Band',
                'Paduan Suara',
                'Tari',
                'Teater',
                'Pengembangan Diri',
                'Debat Bahasa Inggris',
                'Public Speaking',

                'Sepak Bola',
                'Basket',
                'Voli',
                'Bulu Tangkis',
                'Renang',
                'Atletik',
                'Pencak Silat',
                'Karate',
                'Taekwondo',

                'STEM',
                'Project Based Learning',
                'Kewarganegaraan Global',
                'Kesehatan Mental',
                'Literasi Digital',
                'Literasi Finansial',
            ]) . ' ' . $this->faker->randomElement([
                'X',
                'XI',
                'XII',
            ]),
            'token' => $this->faker->randomElement([false, true]),
            'durasi' => $this->faker->numberBetween(30, 120),
            'acak_soal' => $this->faker->randomElement([false, true]),
            'jadwal_mulai' => now(),
            'jadwal_selesai' => now()->addHours(2),
        ];
    }
}
